const RouteName = {
  SPLSH: 'SplashScreen',
  TAB_HOME: 'Home',
  SWIPER_SCREEN: 'Swiperscreen',
  LOGIN_SCREEN: 'LoginScreen',
  REGISTER_SCREEN: 'Register',
  OTP_VERYFY_SCREEN: 'OtpVeryfiveScreen',
  HOME_SCREEN: 'HomeScreen',
  REGIATRAION_SUCCESSFULL: 'RegistrationSuccessful',
  HOME_TAB_SET: 'Home',
  MY_COURSES_TAB: 'Customer',
  EXAM_TAB: 'Contacts',
  WHISHILIST_TAB: 'Chat',
  PROFILE_TAB: 'Settings',
  ADD_MEETING_SCREEN: 'AddMeetingScreen',
  ADD_TASK_SCREEN: 'AddTaskScreen',
  ADD_CALL_SCREEN: 'AddCallScreen',
  TAKS_SCREEN: 'TaskScreen',
  HOME_TAB_SEARCH_SCREEN: 'HomeTabSearchScreen',
  SELECT_MODULES_SCREEN: 'SelectModuleSearch',
  // FEED_BACK_SCREEN: "DraweFeedback",
  NEW_LEADS_SCREEN: 'NewLeadsScreen',
  FEED_BACK_SCREEN: 'DraweFeedback',
  LEAD_SETTINGS_SCREEN: 'DrawerSettings',
  UNSYNCEDRECORD_SCREEN: 'DrawerUnsyncedRecords',
  DRAWERPARTI_CULARTABSCREEN: 'DrawerParticularTasks',
  TASK_DETAILS_SCREEN: 'TaskDetailsScreen',
  DRAWER_MEETINGS: 'DrawerMeeting',
  LEAD_DATA_OPEN_SCREEN: 'LeadDataOpen',
  ADD_NOTE_SCREEN: 'AddNoteScreen',
  ACCOUNT_SCREEN: 'AccountScreen',
  DRAWER_LEAD_MAP: 'DrawerLeadMap',
  MEETINGS_DETAILS_SCREEN: 'MeetingsDetails',
  DRAWER_CALLS_SCREEN: 'DrawerCalls',
  CALLS_DETAILS_SCREEN: 'CallsDetailsScreen',
  HOME: 'Home',
  LOGIN: 'Login',
  CUSTOMER_DETAIL: 'CustomerDetail',
  NEW_CUSTOMER: 'NewCustomer',
  TICKET_DETAIL: 'TicketDetail',
  NOTIFICATIONS: 'Notifications',
  PAYMENTDETAIL: 'PaymentDetail',
  MESSAGE: 'Message',
};
export default RouteName;
