import React, { useState } from "react";
import { View, Text, TouchableOpacity, KeyboardAvoidingView, Modal, Switch, ScrollView, Pressable } from "react-native";
import IconF from 'react-native-vector-icons/AntDesign';
import { Settings, Style } from '../../styles';

const SettingsScreen = () => {
  const [isEnabled, setIsEnabled] = useState(false);
  const toggleSwitch = () => setIsEnabled(previousState => !previousState);
  const [okbutton, Setokbutton] = useState('');

  var alertdata = {
    'logout': " Deleted Successfully",
  }
  const onoknutton = () => {
    okbutton;
  }

  return (
    <>
      <View style={[Style.minstyleviewphotograpgyTwo]}>
        <ScrollView
          keyboardShouldPersistTaps="handled"
          contentContainerStyle={Style.contentContainerStyle}>
          <KeyboardAvoidingView enabled>
            <View style={Settings.keybordtopviewstyle}>
              <View style={Settings.minflexview}>
                <View style={Settings.togglrswitchflex}>
                  <View>
                    <Text style={Settings.cellulardatatext}>Lead Data</Text>
                  </View>
                </View>
                <View style={Settings.toggleswotchview}>
                  <Text style={Settings.downlodtoggleswitchtext}>
                    Enalble Or disable Leads
                  </Text>
                  <View>
                    <Switch
                      trackColor={{ false: "lightgray", true: "lightgray" }}
                      thumbColor={isEnabled ? "hsl(214.3, 83.2%, 51%)" : "white"}
                      ios_backgroundColor="#3e3e3e"
                      onValueChange={toggleSwitch}
                      value={isEnabled}
                    />
                  </View>
                </View>
                <Text style={Settings.cellulardatatext}>Leads</Text>
                <View style={Settings.righticonminview}>
                  <View>
                    <Text style={Settings.standardrecommedtext}>New Lead (recommended)</Text>
                    <Text style={Settings.downloadfastertext}>Enables this features for recommended</Text>
                  </View>
                  <View>
                    <IconF
                      size={30}
                      name="check"
                      style={Settings.chekiconstyle}
                    />
                  </View>
                </View>
                <View style={Settings.righticonminview}>
                  <View>
                    <Text style={Settings.standardrecommedtext}>Dislpay Field</Text>
                    <Text style={Settings.downloadfastertext}>Full Name, Emails </Text>
                  </View>
                </View>
                <Text style={Settings.offlinedoenloadstextset}>Sync</Text>
                <View style={Settings.righticonminview}>
                  <View style={Settings.bodysettextwidth}>
                    <Text style={Settings.standardrecommedtext}>Synce Changes</Text>
                    <Text style={Settings.downloadfastertext}>Syncing leads to a CRM. Sync all leads generated by a Lead Generation campaign. Even if the sync is set up after the campaign begins, existing leads and leads </Text>
                  </View>
                  <View>
                    <IconF
                      size={30}
                      name="check"
                      style={Settings.chekiconstyle}
                    />
                  </View>
                </View>

              </View>
            </View>
          </KeyboardAvoidingView>
        </ScrollView>
      </View>

    </>
  );
};
export default SettingsScreen;
